/*
 * generated by Xtext
 */
package at.caks.eglipse.lang.program;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProgramRuntimeModule extends AbstractProgramRuntimeModule {

}
