/*
* generated by Xtext
*/
package at.caks.eglipse.lang.program.ui.contentassist;

import at.caks.eglipse.lang.program.ui.contentassist.AbstractProgramProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ProgramProposalProvider extends AbstractProgramProposalProvider {

}
