/*
* generated by Xtext
*/
package at.caks.eglipse.lang.program;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ProgramUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.caks.eglipse.lang.program.ui.internal.ProgramActivator.getInstance().getInjector("at.caks.eglipse.lang.program.Program");
	}
	
}
