/*
* generated by Xtext
*/
package at.caks.eglipse.lang.glsl.ui.contentassist;

import at.caks.eglipse.lang.glsl.ui.contentassist.AbstractGlslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GlslProposalProvider extends AbstractGlslProposalProvider {

}
