/*
* generated by Xtext
*/
package at.caks.eglipse.lang.program.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ProgramAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("at/caks/eglipse/lang/program/parser/antlr/internal/InternalProgram.tokens");
	}
}
