/*
* generated by Xtext
*/
package at.caks.eglipse.lang.glsl.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.jface.viewers.StyledString;
import org.eclipse.jface.viewers.StyledString.Styler;
import org.eclipse.swt.SWT;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.graphics.RGB;
import org.eclipse.xtext.ui.editor.utils.TextStyle;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.eclipse.xtext.ui.label.StylerFactory;

import at.caks.eglipse.lang.glsl.glsl.Constructor;
import at.caks.eglipse.lang.glsl.glsl.FunctionPrototype;
import at.caks.eglipse.lang.glsl.glsl.InAttributeDeclaration;
import at.caks.eglipse.lang.glsl.glsl.InOutAttributeDeclaration;
import at.caks.eglipse.lang.glsl.glsl.OutAttributeDeclaration;
import at.caks.eglipse.lang.glsl.glsl.Parameter;
import at.caks.eglipse.lang.glsl.glsl.Symbol;
import at.caks.eglipse.lang.glsl.glsl.UniformDeclaration;
import at.caks.eglipse.lang.glsl.services.GlslGrammarAccess.AttributeDeclarationElements;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * TextStyle
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class GlslLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public GlslLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	String text(Constructor ele) {
		return "Constructor of " + ele.getType().getName();
	}
	
	
	String text(FunctionPrototype ele) {
		StringBuilder b = new StringBuilder();
		b.append(ele.getType().getName() + " " + ele.getName() + "(");
		for (Parameter p : ele.getParams()) {
			b.append(p.getType().getName());
			if (ele.getParams().indexOf(p) != ele.getParams().size() - 1) b.append(", ");
		}
		b.append(")");
		return b.toString();
	}
	
	String image(Symbol s) {
		return "symbol.gif";
	}
	
	String image(UniformDeclaration u) {
		return "uniform.gif";
	}
	
	String image(InOutAttributeDeclaration u) {
		return "inout.gif";
	}
	
	
	String image(OutAttributeDeclaration u) {
		return "out.gif";
	}
	
//	String text(InAttributeDeclaration d) {
//		return d.getQualifier() + " " + d.getType().getName() + " " + d.getName();
//	}
	
	@Inject
	private StylerFactory stylerFactory;

	
	Object text(InAttributeDeclaration d) {
		StyledString s = new StyledString();
		int begin = 0;
		String add = d.getQualifier();
		s.append(add);
		s.setStyle(begin, add.length(), stylerFactory.createXtextStyleAdapterStyler(getQualifierTextStyle()));
		s.append(" ");
		begin += add.length() + 1;
		add = d.getType().getName();
		s.append(add);
		s.setStyle(begin, add.length(), stylerFactory.createXtextStyleAdapterStyler(getTypeTextStyle()));
		s.append(" ");
		begin += add.length() + 1;
		add = d.getName();
		s.append(add);
		//s.setStyle(s.length(), add.length(), stylerFactory.createXtextStyleAdapterStyler(getQualifierTextStyle()));
		return s;
	}
	
	Object text(OutAttributeDeclaration d) {
		StyledString s = new StyledString();
		int begin = 0;
		String add = d.getQualifier();
		s.append(add);
		s.setStyle(begin, add.length(), stylerFactory.createXtextStyleAdapterStyler(getQualifierTextStyle()));
		s.append(" ");
		begin += add.length() + 1;
		add = d.getType().getName();
		s.append(add);
		s.setStyle(begin, add.length(), stylerFactory.createXtextStyleAdapterStyler(getTypeTextStyle()));
		s.append(" ");
		begin += add.length() + 1;
		add = d.getName();
		s.append(add);
		//s.setStyle(s.length(), add.length(), stylerFactory.createXtextStyleAdapterStyler(getQualifierTextStyle()));
		return s;
	}
	
	Object text(InOutAttributeDeclaration d) {
		StyledString s = new StyledString();
		int begin = 0;
		String add = d.getQualifier();
		s.append(add);
		s.setStyle(begin, add.length(), stylerFactory.createXtextStyleAdapterStyler(getQualifierTextStyle()));
		s.append(" ");
		begin += add.length() + 1;
		add = d.getType().getName();
		s.append(add);
		s.setStyle(begin, add.length(), stylerFactory.createXtextStyleAdapterStyler(getTypeTextStyle()));
		s.append(" ");
		begin += add.length() + 1;
		add = d.getName();
		s.append(add);
		//s.setStyle(s.length(), add.length(), stylerFactory.createXtextStyleAdapterStyler(getQualifierTextStyle()));
		return s;
	}
	
	protected TextStyle getQualifierTextStyle() {
		TextStyle textStyle = new TextStyle();
		textStyle.setColor(new RGB(50, 177, 71));
		return textStyle;
	}
	
	protected TextStyle getTypeTextStyle() {
		TextStyle textStyle = new TextStyle();
		textStyle.setColor(new RGB(149, 125, 71));
//		textStyle.setStyle(SWT.BOLD);
		return textStyle;
	}

	
	
	String image(InAttributeDeclaration u) {
		return "in.gif";
	}
	
	
/*
	//Labels and icons can be computed like this:
	
	String text(MyModel ele) {
	  return "my "+ele.getName();
	}
	 
    String image(MyModel ele) {
      return "MyModel.gif";
    }
    
*/
}
