/*
 * generated by Xtext
 */
package org.eglipse.lang.glsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eglipse.lang.glsl.ui.internal.GlslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GlslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GlslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GlslActivator.getInstance().getInjector(GlslActivator.ORG_EGLIPSE_LANG_GLSL_GLSL);
	}
	
}
