/*
 * generated by Xtext
 */
package at.caks.eglipse.lang.program.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ProgramUiModule extends at.caks.eglipse.lang.program.ui.AbstractProgramUiModule {
	public ProgramUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
