/*
 * generated by Xtext
 */
package org.eglipse.lang.glsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GlslRuntimeModule extends org.eglipse.lang.glsl.AbstractGlslRuntimeModule {

}
