/*
 * generated by Xtext
 */
package at.caks.eglipse.lang.glsl;

import at.caks.eglipse.lang.glsl.typesystem.GLSLTypeSystem;

import com.google.inject.Binder;

import de.itemis.xtext.typesystem.ITypesystem;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class GlslRuntimeModule extends at.caks.eglipse.lang.glsl.AbstractGlslRuntimeModule {

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
	}

	public Class<? extends ITypesystem> bindITypestem() {
		return GLSLTypeSystem.class;   
	}
}
