/*
* generated by Xtext
*/
package org.eglipse.lang.glsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GlslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eglipse.lang.glsl.ui.internal.GlslActivator.getInstance().getInjector("org.eglipse.lang.glsl.Glsl");
	}
	
}
