/*
 * generated by Xtext
 */
package at.caks.eglipse.lang.glsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

import at.caks.eglipse.lang.glsl.ui.highlight.GLSLAntlrTokenToAttributeIdMapper;
import at.caks.eglipse.lang.glsl.ui.highlight.GLSLHighlightingConfiguration;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GlslUiModule extends at.caks.eglipse.lang.glsl.ui.AbstractGlslUiModule {
	public GlslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public void configure(Binder binder) {
		
		binder.bind(IHighlightingConfiguration.class).to(GLSLHighlightingConfiguration.class);
		binder.bind(AbstractAntlrTokenToAttributeIdMapper.class).to(GLSLAntlrTokenToAttributeIdMapper
.class);
		
		super.configure(binder);
	}
	
}
