/*
 * generated by Xtext
 */
package at.caks.eglipse.lang.program.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ProgramExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return at.caks.eglipse.lang.program.ui.internal.ProgramActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return at.caks.eglipse.lang.program.ui.internal.ProgramActivator.getInstance().getInjector("at.caks.eglipse.lang.program.Program");
	}
	
}
